// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ``
///`

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZv6ZXzQRn1WIoQ_4dwfkpZBpr1t_VSMg',
    appId: '1:696654367155:android:841a334b9e54818a5e23c6',
    messagingSenderId: '696654367155',
    projectId: 'teamnougattask-3',
    storageBucket: 'teamnougattask-3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH_nP5f9ibLF65lixkQkl8k6ucy-yWQ4I',
    appId: '1:696654367155:ios:bc524fd79537d4d35e23c6',
    messagingSenderId: '696654367155',
    projectId: 'teamnougattask-3',
    storageBucket: 'teamnougattask-3.firebasestorage.app',
    iosBundleId: 'com.example.rudrakshaTask3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH_nP5f9ibLF65lixkQkl8k6ucy-yWQ4I',
    appId: '1:696654367155:ios:bc524fd79537d4d35e23c6',
    messagingSenderId: '696654367155',
    projectId: 'teamnougattask-3',
    storageBucket: 'teamnougattask-3.firebasestorage.app',
    iosBundleId: 'com.example.rudrakshaTask3',
  );
}
